### ISSUE TITLE
Failure to setup integration if device is not turned on.

### ISSUE THREAD

**Issue by BottlecapDave** [nagyrobi/media_player.linkplay#116]
I have the following configuration

```yaml
platform: linkplay
uuid: !secret office_speaker_uuid
host: !secret office_speaker_ip
name: Office
icecast_metadata: 'StationNameSongTitle'
multiroom_wifidirect: False
sources: {}
```

If I restart my HA instance with the device turned off, then the integration fails to setup the entity. It's failing at line 273 of `media_player.py` stating that `response.status` is not allowed because `response` is None. I've fixed this in my local instance and happy to raise an MR which changes this line from

```yaml
response.status,
```
to

```yaml
response.status if response is not None else "UNKNOWN",
```
