### ISSUE TITLE
Up2stream becomes unavailabe

### ISSUE THREAD

**Issue by staxza** [nagyrobi/media_player.linkplay#121]
If you switch on an Up2stream amp or streamer it does not connect.  I have to reboot HA first for it to re-connect

**Comment by rogelio-o** [comment]
I'm having the same issues. The problem is that if the API is not available when starting HA, the component falls back the protocol to HTTPS instead of HTTP. When the instance is up again, the component asks it with HTTPS even if it uses HTTP, which makes it impossible to connect to it anymore until you restart HA and the protocol is configured to HTTP again.

To avoid this, I would add the protocol as an optional configuration parameter(we would also be preventing breaking changes if the parameter is optional).

**Comment by rogelio-o** [comment]
@staxza you just have to configure your instance like this (using version 3.1.9):

```
media_player:
    - platform: linkplay
      host: 192.168.1.11
      protocol: http
      ...
```
