### ISSUE TITLE
led_off doesn't work for Arylics anymore

### ISSUE THREAD

**Issue by jclsn** [nagyrobi/media_player.linkplay#128]
The title says it all. This used to work. Shortly after turning on the device, the LED would turn off. Now nothing happens. Probably since the last update

My config

```yaml
media_player:
    - platform: linkplay
      host: 192.168.184.107
      name: Arylic Wohnzimmer
      icecast_metadata: 'StationNameSongTitle'
      multiroom_wifidirect: True
      led_off: True
      sources: 
        {
          'optical': 'Optical', 
          'line-in': 'Line-In', 
          'bluetooth': 'Bluetooth',
          'udisk': 'USB stick',
        }
```
