### ISSUE TITLE
2024.8 Linkplay in core

### ISSUE THREAD

**Issue by pergolafabio** [nagyrobi/media_player.linkplay#150]
Seems LinkPlay will be an official core integration soon
So this HACS is not necessary anymore?

https://rc.home-assistant.io/integrations/linkplay/

**Comment by nagyrobi** [comment]
Oh wow, finally! I can deprecate this as soon as it will be released.

**Comment by Thrasher2020** [comment]
I tried using it - there's nowhere to actually configure it like the yaml version.

**Comment by nagyrobi** [comment]
It's autodetected. No need for YAMLs.
It's also pretty generic, eg. can't change the input source names.

**Comment by pergolafabio** [comment]
Yeah, probably more PR are coming to make it better...

**Comment by Thrasher2020** [comment]
Exactly. Mine is pretty heavily configured via yaml for icecast, LastFM and lots of sources etc. This new one doesn't allow for any of that so I think I'll stick with the HACS version :)

**Comment by pergolafabio** [comment]
Yeah, probably more PR are coming to make it better...

**Comment by pergolafabio** [comment]
maybe @nagyrobi  can give a help to the core team about improving it? :-)

**Comment by nagyrobi** [comment]
**From now, the `linkplay` custom component for Home Assistant is deprecated, and unsupported! Starting with Home Assistant 2024.08 release, Linkplay chipset based media players are officially supported without the need of any custom component.**

To switch to the official LinkPlay integration starting from **2024.08**, follow these steps:
* Remove tle current `linkplay` configuration from your configuration.yaml.
* Restart Home-Assistant.
* Delete the custom component through HACS or manually by deleting the `custom_components/linkplay` folder.
* Restart Home-Assistant again. Your players will be automatically discovered, a notification popup will inform you on this.

For any bugs and feature requests, please use the official Home Assistant channels.

**Comment by pergolafabio** [comment]
that was quick :-)

**Comment by pergolafabio** [comment]
anyway, thnx a lot for this custom, i really enjoyed it!!

**Comment by nagyrobi** [comment]
When I took this over from @limych, in 2020, Home Assitant codebase was much more simpler and easier to understand. Over time, it grew to be so overcomplicated and abstracted that I simply couldn't keep up as an amateur programmer. Tried to watch the way other built-in media players codebase evolves, but from a point on I had to give up.

My personal opinion is that certain aspects of the development are not going the best way but then again, what do I know.

Additionally, I got a bit frustrated about the way certain Linkplays call home to third party servers, so I really like the news shared in https://github.com/nagyrobi/home-assistant-custom-components-linkplay/issues/142, which would require a completely new integration/component anyway.

**Comment by nagyrobi** [comment]
> maybe @nagyrobi can give a help to the core team about improving it? :-)

Already found a bug, [reported it](https://github.com/home-assistant/core/issues/123051), and they fixed it.

**Comment by pergolafabio** [comment]
glad you are helping already, good job!
lets hope it gets merged in the beta, before it gets out :-)

**Comment by nagyrobi** [comment]
Meanwhile everybody who wants to see their devices autodetected **by brand and model** in HA, please make a PR, based on the `project` field seen in `/httpapi.asp?command=getStatusEx`, by adding to the file `homeassistant/components/linkplay/utils.py`.

For example I added some Arylics I know in https://github.com/home-assistant/core/pull/123056

**Comment by pergolafabio** [comment]
hey @nagyrobi , just tested the new core, but with yours custom, i used this service:

```
                  action: call-service
                  service: linkplay.preset
                  service_data:
                    entity_id: media_player.luidspreker_buiten
                    preset: 1
```
any idea if thats possible too to play presets?

**Comment by nagyrobi** [comment]
Don't think so. Make a Feature Request in HA core.

**Comment by pergolafabio** [comment]
seems also this one doesnt work?

```
                  action: call-service
                  service: media_player.play_media
                  service_data:
                    entity_id: media_player.luidspreker_buiten
                    media_content_id: 'http://opml.radiotime.com/Tune.ashx?id=s10861'
                    media_content_type: url
```

any idea how the new format will be?

thnx!

**Comment by pergolafabio** [comment]
done

https://github.com/home-assistant/core/issues/123372

**Comment by nagyrobi** [comment]
> any idea how the new format will be?

It will be the way the developer who makes it, wants to...

**Comment by pergolafabio** [comment]
yeah, tried to play some basic mp3 , didnt work either... not sure what does work?

Tried some basic commands now, this works on my google hub:

```
action: media_player.play_media
target:
  entity_id: media_player.google_hub
data:
  media_content_type: playlist
  media_content_id: 'https://icecast.vrtcdn.be/mnm-high.mp3'
```

and the same on my linkplay device:

```
action: media_player.play_media
target:
  entity_id: media_player.luidspreker_buiten
data:
  media_content_type: playlist
  media_content_id: 'https://icecast.vrtcdn.be/mnm-high.mp3'
```

gives me:

`Failed to perform the action media_player.play_media. Invalid media source URI`

also tried like content_type : music ...

reverted back yo your custom for now :-)
