### ISSUE TITLE
Audiopro A10

### ISSUE THREAD

**Issue by meijer3** [nagyrobi/media_player.linkplay#60]
My simple config looks like:
```
media_player:
  - platform: linkplay
    host: 192.168.20.145
    name: AudioPro A10
    volume_step: 1
    sources: { "line-in": "line-in" }
```
Everything works fine (nice intergation)
![image](https://user-images.githubusercontent.com/45625341/151023397-840e5fc0-80b4-4e9b-b611-62fcce71edfc.png)
Except my on / off button.
Does not work at loveance cards and not with node-red.

Maybe a hint is in the enity window, because there is no on/off button.
![image](https://user-images.githubusercontent.com/45625341/151023789-d6a25989-8327-4f92-81f3-0b0a5bdfbc9a.png)

And separate issue, but sometimes it starts by it self, without music.. Maybe not relevant, but then, maybe it is
