### ISSUE TITLE
HA Configuration Validation stuck after editing config

### ISSUE THREAD

**Issue by xbavnu** [nagyrobi/media_player.linkplay#65]
Hi,
I am new to HA, so I am probably just missing an important piece of information. But as soon as I add linkplay to the configuration.yaml, the config validation doesn't work anymore.

I installed linkplay via HACS, restarted everything and am adding following lines to the config:

```
media_player:
    - platform: linkplay
      host: 192.168.178.52
      name: pc speaker
```

Without these lines the config validation works jsut fine. After adding these lines the validation gets stuck and never shows "Configuration valid!" or similar.

**Comment by nagyrobi** [comment]
What's the exact message?

You likely have an indentation problem:
```
media_player:
  - platform: linkplay
    host: 192.168.178.52
    name: pc speaker
```
