### ISSUE TITLE
Currently playing media meta-data not being send with media.player-play.media

### ISSUE THREAD

**Issue by TheBigSadd** [nagyrobi/media_player.linkplay#73]
When i use the media_player.play_media service and send an url, thumbnail and name. I can't see the thumbnail and name that i specified. 

Here is code:
```yaml
      - entity: media_player.overkapping_aan_tuinhuis
        type: custom:mini-media-player
        name: Plafondspeakers / Veranda Aan Tuinhuis
        info: short
        icon: mdi:speaker
        artwork: material
        hide:
          power: true
          icon: true
        shortcuts:
          columns: 4
          column_height: 80
          label: "> Radio Zenders"
          list:
            #RADIO 538
            - type: service
              image: /local/radiozenders/538.png
              name: Radio 538
              id: media_player.play_media
              data:
                media_content_type: url
                media_content_id: >-
                  http://25493.live.streamtheworld.com/RADIO538.mp3
                extra:
                  title: Radio 538
                  thumb: >-
                    /local/radiozenders/538.png
                entity_id: media_player.overkapping_aan_tuinhuis
```
- In this image you can see that the player above (chromecast) does get the meta data but the LINK player below doesn't:
![image](https://user-images.githubusercontent.com/29535818/168069929-af09ae5f-c295-4be6-8270-aea4d65bb57f.png)

**Comment by nagyrobi** [comment]
That is not supported. The integration is designed to retrieve data from Icecast service by itself.

Just tested the radio stream url you provided (http://25493.live.streamtheworld.com/RADIO538.mp3) and currently broadcasted on air artist and title is properly decoded from the stream headers. 

Moreover if you configure a LastFm API key, you'll get cover arts too, all automatic.
Much better than having to provide a static logo by yourself.

**Comment by TheBigSadd** [comment]
I have created a Last.FM API key and i have entered it into my config. Sadly i still dont get artist info or a album cover

```yaml
media_player:
    - platform: linkplay
      host: 10.16.0.96
      name: Overkapping
      multiroom_wifidirect: False
      lastfm_api_key: #######################
      icecast_metadata: 'StationName'
```

![image](https://user-images.githubusercontent.com/29535818/168087302-dad1e370-f3c3-49eb-bb3d-e5d36d511163.png)
