### ISSUE TITLE
Linkplay entities unavailable in Home Assistant?

### ISSUE THREAD

**Issue by kylepyke** [nagyrobi/media_player.linkplay#94]
Hi Robert! Thanks for all of your work on this.

I'm trying to integrate my Wiim minis into Home Assistant, and it seems they appear as unavailable. They are linkplay devices– are they supported by this integration? I've verified the below IPs and uuids are correct.

```
media_player:
  - platform: linkplay
    host: 192.168.1.252
    name: Console Player
    volume_step: 5
    uuid: "FF9700169D79193339EF44F3"
    icecast_metadata: "StationNameSongTitle"
    multiroom_wifidirect: False
    sources: { "line-in": "Record Player", "bluetooth": "Bluetooth" }
    common_sources: !include linkplay-radio-sources.yaml
    
  - platform: linkplay
    host: 192.168.1.237
    name: Kitchen
    icecast_metadata: "Off" # valid values: 'Off', 'StationName', 'StationNameSongTitle'
    sources: { "bluetooth": "Bluetooth" }
    common_sources: !include linkplay-radio-sources.yaml
    uuid: "FF9700169841A4CB6A81120D"
```
